package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/doc"
	"go/format"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"unicode"

	"golang.org/x/tools/go/packages"
)

const modulePath = "github.com/sahilkhaire/gox"
const docVersion = "7"

var packageGroups = []struct {
	label    string
	packages []string
}{
	{"Utilities", []string{"cond", "slice", "maputil", "str", "set", "buffer", "async", "path", "url"}},
	{"I/O & OS", []string{"env", "fs", "err", "exec", "osutil", "stream", "compress", "csv", "archive"}},
	{"Web", []string{"http", "client", "log", "ws"}},
	{"Data", []string{"json", "validate", "db", "redis", "mongo"}},
	{"Security", []string{"crypto", "jwt", "id", "auth"}},
	{"Infrastructure", []string{"cache", "event", "cron", "queue", "mail", "time", "semver"}},
}

var packageNodeAnalog = map[string]string{
	"cond": "ternary ? :, nullish ??", "slice": "lodash / Array.*", "maputil": "lodash object utils",
	"str": "string helpers", "set": "Set", "err": "http-errors", "env": "dotenv / process.env",
	"fs": "fs.promises", "path": "path", "async": "Promise.all, timers", "buffer": "Buffer",
	"url": "url, querystring", "http": "express, cors, helmet, morgan", "client": "axios, fetch",
	"log": "winston, pino", "validate": "zod, joi", "json": "JSON.parse/stringify",
	"db": "knex", "redis": "ioredis", "mongo": "mongoose", "crypto": "crypto, bcrypt",
	"jwt": "jsonwebtoken", "id": "uuid, nanoid", "auth": "passport", "cache": "lru-cache",
	"event": "EventEmitter", "cron": "node-cron", "queue": "bull", "mail": "nodemailer",
	"time": "moment, dayjs (package timex)", "stream": "Node stream", "compress": "zlib",
	"semver": "semver", "ws": "ws", "archive": "archiver", "csv": "papaparse",
	"exec": "child_process", "osutil": "os",
}

var packageQuickStart = map[string]string{
	"cond":     "label := cond.If(score >= 60, \"pass\", \"fail\")",
	"slice":    "evens := slice.Filter(nums, func(n int) bool { return n%2 == 0 })",
	"maputil":  "picked := maputil.Pick(cfg, \"host\", \"port\")",
	"http":     "app := goxhttp.New()\napp.Get(\"/health\", func(c *goxhttp.Ctx) error {\n    return c.JSON(200, map[string]string{\"status\": \"ok\"})\n})",
	"client":   "res, err := client.Get(ctx, \"https://api.example.com/users\")",
	"env":      "port := env.Get(\"PORT\", \"8080\")",
	"db":       "row, err := db.From(\"users\").WhereEq(\"id\", id).First(ctx, &user)",
	"validate": "if err := validate.Validate(&user); err != nil { /* return 400 */ }",
	"jwt":      "token, err := jwt.Sign(claims, secret, jwt.SignOptions{ExpiresIn: time.Hour})",
}

type symbolDoc struct {
	Pkg       string
	Name      string
	Kind      string // func, type, const, var, method
	Signature string
	Summary   string
	Node      string
	Receiver  string
	Slug      string
}

type coverageEntry struct {
	Pkg    string `json:"package"`
	Symbol string `json:"symbol"`
	Kind   string `json:"kind"`
	Page   string `json:"page"`
	OK     bool   `json:"ok"`
}

func main() {
	goxSrc := flag.String("gox", envOr("GOX_SRC", "../gox"), "path to gox library root")
	outDir := flag.String("out", "docs", "website docs root")
	checkOnly := flag.Bool("check", false, "verify coverage only; exit 1 if pages missing")
	flag.Parse()

	websiteRoot, _ := os.Getwd()
	goxAbs, err := filepath.Abs(filepath.Join(websiteRoot, *goxSrc))
	if err != nil {
		fatal(err)
	}
	docsRoot := filepath.Join(websiteRoot, *outDir)
	packagesDir := filepath.Join(docsRoot, "packages")

	nodeMap := loadNodeMapping(filepath.Join(goxAbs, "docs", "node-mapping.md"))
	loadAutoEnrichments(filepath.Join(goxAbs, "docs", "node-mapping.md"))
	testExamples = loadTestExamples(goxAbs)

	var allPkgs []string
	for _, t := range packageGroups {
		allPkgs = append(allPkgs, t.packages...)
	}

	var coverage []coverageEntry
	var sidebar bytes.Buffer
	sidebar.WriteString("// Code generated by scripts/gendocs; DO NOT EDIT.\n")
	sidebar.WriteString("export const generatedSidebar = {\n")
	sidebar.WriteString("  '/packages/': [\n")

	for _, group := range packageGroups {
		sidebar.WriteString(fmt.Sprintf("    { text: '%s', collapsed: false, items: [\n", escapeJS(group.label)))
		for _, pkgName := range group.packages {
			pkgDocs, syms, err := loadPackage(goxAbs, pkgName)
			if err != nil {
				fmt.Fprintf(os.Stderr, "warn: %s: %v\n", pkgName, err)
				continue
			}
			if !*checkOnly {
				if err := writePackageIndex(packagesDir, pkgName, pkgDocs, syms); err != nil {
					fatal(err)
				}
				if err := writeCookbookPage(packagesDir, pkgName); err != nil {
					fatal(err)
				}
			}
			for _, sym := range syms {
				sym.Node = nodeMap.lookup(pkgName, sym.Name, sym.Receiver)
				pageRel := filepath.Join("packages", pkgName, sym.Slug+".md")
				pagePath := filepath.Join(docsRoot, pageRel)
				if *checkOnly {
					coverage = append(coverage, coverageEntry{pkgName, sym.Name, sym.Kind, pageRel, fileExists(pagePath)})
					continue
				}
				exists := fileExists(pagePath)
				if !exists || needsRegen(pagePath) {
					if err := writeSymbolPage(pagePath, sym, pkgDocs); err != nil {
						fatal(err)
					}
					exists = true
				}
				coverage = append(coverage, coverageEntry{pkgName, sym.Name, sym.Kind, pageRel, exists})
			}
			sidebar.WriteString(fmt.Sprintf("      {\n        text: '%s',\n        collapsed: true,\n        items: [\n", pkgName))
			sidebar.WriteString(fmt.Sprintf("          { text: 'Overview', link: '/packages/%s/' },\n", pkgName))
			if hasCookbook(pkgName) {
				sidebar.WriteString(fmt.Sprintf("          { text: '📖 Cookbook', link: '/packages/%s/cookbook' },\n", pkgName))
			}
			for _, sym := range syms {
				label := sym.Name
				if sym.Kind == "method" {
					label = sym.Receiver + "." + sym.Name
				}
				sidebar.WriteString(fmt.Sprintf("          { text: '%s', link: '/packages/%s/%s' },\n", label, pkgName, sym.Slug))
			}
			sidebar.WriteString("        ]\n      },\n")
		}
		sidebar.WriteString("    ]},\n")
	}
	sidebar.WriteString("  ]\n}\n")

	sidebarPath := filepath.Join(docsRoot, ".vitepress", "sidebar.generated.ts")
	if err := os.MkdirAll(filepath.Dir(sidebarPath), 0o755); err != nil {
		fatal(err)
	}
	if !*checkOnly {
		if err := os.WriteFile(sidebarPath, sidebar.Bytes(), 0o644); err != nil {
			fatal(err)
		}
	}
	if err := writeCoverage(websiteRoot, coverage); err != nil {
		fatal(err)
	}
	if !*checkOnly {
		fmt.Printf("generated %d symbols across %d packages\n", len(coverage), len(allPkgs))
	} else {
		fmt.Printf("checked %d symbols\n", len(coverage))
	}

	missing := 0
	for _, c := range coverage {
		if !c.OK {
			missing++
			fmt.Fprintf(os.Stderr, "missing: %s.%s (%s)\n", c.Pkg, c.Symbol, c.Page)
		}
	}
	if missing > 0 {
		os.Exit(1)
	}
}

func loadPackage(goxRoot, pkgName string) (*doc.Package, []symbolDoc, error) {
	importPath := modulePath + "/" + pkgName
	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedFiles | packages.NeedCompiledGoFiles |
			packages.NeedTypes | packages.NeedTypesInfo | packages.NeedSyntax,
		Dir: goxRoot,
	}
	pkgs, err := packages.Load(cfg, importPath)
	if err != nil {
		return nil, nil, err
	}
	if len(pkgs) == 0 || pkgs[0].Errors != nil {
		if len(pkgs) > 0 && len(pkgs[0].Errors) > 0 {
			return nil, nil, pkgs[0].Errors[0]
		}
		return nil, nil, fmt.Errorf("package not found: %s", importPath)
	}
	pkg := pkgs[0]
	fset := token.NewFileSet()
	var astFiles []*ast.File
	for _, file := range pkg.CompiledGoFiles {
		f, err := parser.ParseFile(fset, file, nil, parser.ParseComments)
		if err != nil {
			return nil, nil, fmt.Errorf("parse %s: %w", file, err)
		}
		astFiles = append(astFiles, f)
	}
	apkg, err := doc.NewFromFiles(fset, astFiles, importPath)
	if err != nil {
		return nil, nil, err
	}
	var syms []symbolDoc
	for _, fn := range apkg.Funcs {
		syms = append(syms, symbolDoc{
			Pkg: pkgName, Name: fn.Name, Kind: "func",
			Signature: formatNode(fset, fn.Decl), Summary: firstSentence(fn.Doc),
			Slug: slugify(fn.Name),
		})
	}
	for _, t := range apkg.Types {
		syms = append(syms, symbolDoc{
			Pkg: pkgName, Name: t.Name, Kind: "type",
			Signature: formatNode(fset, t.Decl), Summary: firstSentence(t.Doc),
			Slug: slugify(t.Name),
		})
		for _, m := range t.Funcs {
			syms = append(syms, symbolDoc{
				Pkg: pkgName, Name: m.Name, Kind: "method", Receiver: t.Name,
				Signature: formatNode(fset, m.Decl), Summary: firstSentence(m.Doc),
				Slug: slugify(t.Name + "-" + m.Name),
			})
		}
	}
	for _, c := range apkg.Consts {
		for _, spec := range c.Names {
			syms = append(syms, symbolDoc{
				Pkg: pkgName, Name: spec, Kind: "const",
				Signature: "const " + spec, Summary: firstSentence(c.Doc),
				Slug: slugify(spec),
			})
		}
	}
	for _, v := range apkg.Vars {
		for _, spec := range v.Names {
			syms = append(syms, symbolDoc{
				Pkg: pkgName, Name: spec, Kind: "var",
				Signature: "var " + spec, Summary: firstSentence(v.Doc),
				Slug: slugify(spec),
			})
		}
	}
	sort.Slice(syms, func(i, j int) bool {
		if syms[i].Kind != syms[j].Kind {
			return kindOrder(syms[i].Kind) < kindOrder(syms[j].Kind)
		}
		return syms[i].Name < syms[j].Name
	})
	return apkg, syms, nil
}

func kindOrder(k string) int {
	switch k {
	case "func":
		return 0
	case "type":
		return 1
	case "method":
		return 2
	case "const":
		return 3
	default:
		return 4
	}
}

func writePackageIndex(dir, pkgName string, apkg *doc.Package, syms []symbolDoc) error {
	pkgDir := filepath.Join(dir, pkgName)
	if err := os.MkdirAll(pkgDir, 0o755); err != nil {
		return err
	}
	analog := packageNodeAnalog[pkgName]
	importPath := modulePath + "/" + pkgName
	subtitle := strings.TrimSpace(apkg.Doc)
	if subtitle == "" {
		subtitle = "Node-friendly helpers for " + analog
	}
	subtitle = collapseWS(subtitle)

	var b strings.Builder
	b.WriteString("---\n")
	b.WriteString(fmt.Sprintf("title: %q\n", pkgName))
	b.WriteString(fmt.Sprintf("package: %q\n", pkgName))
	b.WriteString(fmt.Sprintf("gox-doc-version: %q\n", docVersion))
	b.WriteString("---\n\n")
	b.WriteString(writePackageHeroHTML(pkgName, analog, importPath, subtitle))

	if pkgName == "time" {
		b.WriteString("::: warning Package identifier\n")
		b.WriteString("Import `github.com/sahilkhaire/gox/time` but use the identifier **`timex`** in code — avoids clashing with Go's standard `time` package.\n")
		b.WriteString(":::\n\n")
	}

	if qs, ok := packageQuickStart[pkgName]; ok {
		b.WriteString("## Quick start\n\n")
		b.WriteString("A minimal example to get going:\n\n")
		b.WriteString("```go\nimport \"" + importPath + "\"\n\n" + qs + "\n```\n\n")
	}
	if hasCookbook(pkgName) {
		b.WriteString(fmt.Sprintf("::: tip Full cookbook\nSee the [**%s cookbook**](/packages/%s/cookbook) for multi-step recipes and real-world patterns.\n:::\n\n", pkgName, pkgName))
	}

	b.WriteString("## What's in this package\n\n")
	if analog != "" {
		b.WriteString("If you have used **" + analog + "** in Node.js, this package is your starting point. ")
	}
	b.WriteString(fmt.Sprintf("Browse **%d documented symbols** below — each page includes Node.js, standard Go, and gox side-by-side examples.\n\n", len(syms)))

	// Group symbols by kind
	groups := map[string][]symbolDoc{}
	order := []string{"func", "type", "method", "const", "var"}
	for _, s := range syms {
		groups[s.Kind] = append(groups[s.Kind], s)
	}
	labels := map[string]string{"func": "Functions", "type": "Types", "method": "Methods", "const": "Constants", "var": "Variables"}

	for _, kind := range order {
		items := groups[kind]
		if len(items) == 0 {
			continue
		}
		b.WriteString("### " + labels[kind] + "\n\n")
		b.WriteString("<table class=\"symbol-table\"><thead><tr><th>Symbol</th><th>Kind</th><th>Summary</th></tr></thead><tbody>\n")
		for _, s := range items {
			link := fmt.Sprintf("/packages/%s/%s", pkgName, s.Slug)
			label := s.Name
			if s.Kind == "method" {
				label = s.Receiver + "." + s.Name
			}
			b.WriteString(fmt.Sprintf("<tr><td><a href=%q>%s</a></td><td><span class=\"kind-pill\">%s</span></td><td>%s</td></tr>\n",
				link, label, s.Kind, escapeTable(escapeHTML(s.Summary))))
		}
		b.WriteString("</tbody></table>\n\n")
	}
	return os.WriteFile(filepath.Join(pkgDir, "index.md"), []byte(b.String()), 0o644)
}

func writeSymbolPage(path string, sym symbolDoc, apkg *doc.Package) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	title := sym.Name
	if sym.Kind == "method" {
		title = sym.Receiver + "." + sym.Name
	}
	pkgIdent := sym.Pkg
	if sym.Pkg == "time" {
		pkgIdent = "timex"
	}
	e, _, hasEnrich := lookupEnrichment(sym.Pkg, sym.Name, sym.Receiver)

	var b strings.Builder
	b.WriteString("---\n")
	b.WriteString(fmt.Sprintf("title: %q\n", title))
	b.WriteString(fmt.Sprintf("package: %q\n", sym.Pkg))
	b.WriteString(fmt.Sprintf("import: %q\n", modulePath+"/"+sym.Pkg))
	if sym.Node != "" {
		b.WriteString(fmt.Sprintf("node: %q\n", sym.Node))
	}
	b.WriteString(fmt.Sprintf("gox-doc-version: %q\n", docVersion))
	b.WriteString("---\n\n")

	nodeLabel := sym.Node
	if nodeLabel == "" {
		nodeLabel = packageNodeAnalog[sym.Pkg]
	}
	b.WriteString(writeAPIMetaHTML(sym.Pkg, nodeLabel, modulePath+"/"+sym.Pkg))
	b.WriteString("\n")

	b.WriteString(fmt.Sprintf("# %s\n\n", title))

	// Overview
	b.WriteString("## Overview\n\n")
	if hasEnrich && e.Description != "" {
		b.WriteString(collapseWS(e.Description) + "\n\n")
	} else if sym.Summary != "" {
		b.WriteString(escapeHTML(sym.Summary) + "\n\n")
	}
	if sym.Node != "" {
		b.WriteString("**Node.js equivalent:** `" + sym.Node + "`\n\n")
	}

	b.WriteString("## Signature\n\n")
	b.WriteString("```go\n" + strings.TrimSpace(sym.Signature) + "\n```\n\n")

	// Compare section with code-group
	b.WriteString("## Compare: Node.js · Standard Go · gox\n\n")
	nodeCode := "// See package overview"
	stdGoCode := standardGoCode(sym, e, hasEnrich)
	goxCode := goxCodeBlock(sym, pkgIdent, e, hasEnrich)

	if hasEnrich && e.Node != "" {
		nodeCode = e.Node
	} else if sym.Node != "" {
		nodeCode = sym.Node
	}

	b.WriteString("::: code-group\n\n")
	b.WriteString("```js [Node.js]\n" + nodeCode + "\n```\n\n")
	b.WriteString("```go [Standard Go]\n" + stdGoCode + "\n```\n\n")
	b.WriteString("```go [gox]\nimport \"" + modulePath + "/" + sym.Pkg + "\"\n\n" + goxCode + "\n```\n\n")
	b.WriteString(":::\n\n")

	if hasEnrich && e.Example != "" {
		b.WriteString("## Example from tests\n\n")
		b.WriteString("Extracted from the gox test suite — runnable patterns used in CI:\n\n")
		b.WriteString("```go\nimport \"" + modulePath + "/" + sym.Pkg + "\"\n\n" + e.Example + "\n```\n\n")
	}

	// Tips
	b.WriteString("## Tips\n\n")
	if hasEnrich && e.Tips != "" {
		b.WriteString(e.Tips + "\n\n")
	} else if hasEnrich && e.When != "" {
		b.WriteString("::: tip When to use gox\n")
		b.WriteString(e.When + "\n")
		b.WriteString(":::\n\n")
	} else {
		b.WriteString("::: tip When to use gox\n")
		b.WriteString(whenToUse(sym) + "\n")
		b.WriteString(":::\n\n")
	}

	if hasEnrich && e.Pitfall != "" {
		b.WriteString("::: warning Watch out\n")
		b.WriteString(e.Pitfall + "\n")
		b.WriteString(":::\n\n")
	}

	related := relatedSymbols(sym, apkg)
	if len(related) > 0 {
		b.WriteString("## Related APIs\n\n")
		for _, r := range related {
			slug := slugify(r)
			if strings.Contains(r, ".") {
				parts := strings.SplitN(r, ".", 2)
				slug = slugify(parts[0] + "-" + parts[1])
			}
			b.WriteString(fmt.Sprintf("- [%s](/packages/%s/%s)\n", r, sym.Pkg, slug))
		}
		b.WriteString("\n")
	}
	b.WriteString(fmt.Sprintf("← [Back to %s package overview](/packages/%s/)\n", sym.Pkg, sym.Pkg))
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

func standardGoCode(sym symbolDoc, e enrichment, ok bool) string {
	if ok && e.StdGo != "" {
		return e.StdGo
	}
	switch sym.Pkg {
	case "slice":
		return "// Manual loop or Go 1.21+ slices package\nfor i, v := range items {\n    // transform v\n}"
	case "cond":
		return "if condition {\n    result = a\n} else {\n    result = b\n}"
	case "http":
		return "func handler(w http.ResponseWriter, r *http.Request) {\n    json.NewEncoder(w).Encode(data)\n}"
	case "env":
		return "v := os.Getenv(\"KEY\")\nif v == \"\" {\n    v = \"default\"\n}"
	case "fs":
		return "data, err := os.ReadFile(path)"
	default:
		return "// Use the underlying stdlib or driver directly.\n// See package overview for escape hatches (e.g. db.SQL, redis.RDB)."
	}
}

func goxCodeBlock(sym symbolDoc, pkgIdent string, e enrichment, ok bool) string {
	if ok && e.Gox != "" {
		return e.Gox
	}
	return goxExample(sym, pkgIdent)
}

func standardGoNote(sym symbolDoc) string {
	switch sym.Pkg {
	case "slice":
		return "Use a `for` loop or Go 1.21+ `slices` package helpers from the standard library."
	case "cond":
		return "Use `if/else` for branching and explicit nil checks instead of `??`."
	case "http":
		return "Use `net/http` with handler functions `func(w http.ResponseWriter, r *http.Request)` or a router like chi/echo directly."
	case "env":
		return "Use `os.Getenv` and `os.Setenv` from the standard library, or a config library like viper."
	case "fs":
		return "Use `os.ReadFile`, `os.WriteFile`, etc. Pass `context.Context` manually for cancellation."
	default:
		return "gox wraps the Go standard library or a trusted dependency with Node-familiar naming. You can use the underlying library directly — see the package overview for escape hatches."
	}
}

func goxExample(sym symbolDoc, pkgIdent string) string {
	name := sym.Name
	if sym.Kind == "method" {
		return fmt.Sprintf("var v %s\nv.%s(/* args */)", sym.Receiver, sym.Name)
	}
	switch sym.Pkg + "." + sym.Name {
	case "slice.Map":
		return "out := slice.Map(items, func(v T) U { return transform(v) })"
	case "cond.If":
		return "label := cond.If(age >= 18, \"adult\", \"minor\")"
	case "cond.Coalesce":
		return "name := cond.Coalesce(maybeName, \"guest\")"
	case "env.Load":
		return "if err := env.Load(); err != nil { /* handle */ }"
	case "env.Get":
		return "port := env.Get(\"PORT\", \"8080\")"
	default:
		if strings.HasPrefix(sym.Signature, "func ") {
			return fmt.Sprintf("// %s\n_ = %s.%s(/* args */)", pkgIdent, pkgIdent, name)
		}
		return fmt.Sprintf("_ = %s.%s", pkgIdent, name)
	}
}

func whenToUse(sym symbolDoc) string {
	return "- Familiar API if you are migrating from Node.js\n- Typed generics and explicit error handling (idiomatic Go underneath)\n- Consistent naming across the gox toolkit"
}

func relatedSymbols(sym symbolDoc, apkg *doc.Package) []string {
	var names []string
	limit := 3
	if sym.Kind == "method" {
		for _, m := range findType(apkg, sym.Receiver) {
			if m != sym.Name && len(names) < limit {
				names = append(names, sym.Receiver+"."+m)
			}
		}
		return names
	}
	for _, fn := range apkg.Funcs {
		if fn.Name != sym.Name && len(names) < limit {
			names = append(names, fn.Name)
		}
	}
	return names
}

func findType(apkg *doc.Package, name string) []string {
	for _, t := range apkg.Types {
		if t.Name == name {
			var ms []string
			for _, m := range t.Funcs {
				ms = append(ms, m.Name)
			}
			return ms
		}
	}
	return nil
}

// nodeMapping maps package -> symbol -> node snippet
type nodeMapping map[string]map[string]string

func loadNodeMapping(path string) nodeMapping {
	data, err := os.ReadFile(path)
	if err != nil {
		return nodeMapping{}
	}
	m := make(nodeMapping)
	rowRe := regexp.MustCompile(`^\|\s*` + "`" + `([^` + "`" + `]+)` + "`" + `\s*\|\s*` + "`" + `([^` + "`" + `]+)` + "`" + `\s*\|`)
	lines := strings.Split(string(data), "\n")
	var currentPkg string
	for _, line := range lines {
		if strings.HasPrefix(line, "## ") {
			h := strings.TrimPrefix(line, "## ")
			if idx := strings.Index(h, " — "); idx > 0 {
				currentPkg = strings.Fields(h[:idx])[0]
			} else {
				currentPkg = strings.Fields(h)[0]
			}
		}
		matches := rowRe.FindStringSubmatch(line)
		if len(matches) != 3 || currentPkg == "" {
			continue
		}
		node, goxExpr := matches[1], matches[2]
		sym := extractSymbol(goxExpr)
		if sym == "" {
			continue
		}
		if m[currentPkg] == nil {
			m[currentPkg] = make(map[string]string)
		}
		m[currentPkg][sym] = node
	}
	return m
}

func extractSymbol(expr string) string {
	expr = strings.TrimSpace(expr)
	if idx := strings.Index(expr, "("); idx > 0 {
		expr = expr[:idx]
	}
	parts := strings.Split(expr, ".")
	if len(parts) == 0 {
		return ""
	}
	last := parts[len(parts)-1]
	if idx := strings.Index(last, "("); idx > 0 {
		last = last[:idx]
	}
	return last
}

func (m nodeMapping) lookup(pkg, name, receiver string) string {
	if receiver != "" {
		if v, ok := m[pkg][name]; ok {
			return v
		}
	}
	if v, ok := m[pkg][name]; ok {
		return v
	}
	return ""
}

func formatNode(fset *token.FileSet, node ast.Node) string {
	var buf bytes.Buffer
	_ = printer.Fprint(&buf, fset, node)
	src := buf.Bytes()
	formatted, err := format.Source(src)
	if err != nil {
		return string(src)
	}
	return string(formatted)
}

func firstSentence(s string) string {
	s = strings.TrimSpace(s)
	if s == "" {
		return ""
	}
	for i, r := range s {
		if r == '.' && i+1 < len(s) && (s[i+1] == ' ' || s[i+1] == '\n') {
			return s[:i+1]
		}
	}
	if len(s) > 120 {
		return s[:117] + "..."
	}
	return s
}

func slugify(s string) string {
	var b strings.Builder
	runes := []rune(s)
	for i, r := range runes {
		if unicode.IsUpper(r) {
			if i > 0 {
				prev := runes[i-1]
				nextLower := i+1 < len(runes) && unicode.IsLower(runes[i+1])
				if unicode.IsLower(prev) || (unicode.IsUpper(prev) && nextLower) {
					b.WriteByte('-')
				}
			}
			b.WriteRune(unicode.ToLower(r))
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

func escapeJS(s string) string {
	return strings.ReplaceAll(s, "'", "\\'")
}

func writeAPIMetaHTML(pkg, node, importPath string) string {
	var b strings.Builder
	b.WriteString(`<div class="api-meta">`)
	if node != "" {
		b.WriteString(fmt.Sprintf(`<span class="api-badge node">Node: %s</span>`, escapeHTML(node)))
	}
	b.WriteString(fmt.Sprintf(`<span class="api-badge import">%s</span>`, escapeHTML(importPath)))
	b.WriteString(`</div>`)
	return b.String()
}

func writePackageHeroHTML(name, node, importPath, subtitle string) string {
	var b strings.Builder
	b.WriteString(`<div class="package-hero">`)
	b.WriteString(`<div class="api-meta">`)
	if node != "" {
		b.WriteString(fmt.Sprintf(`<span class="api-badge node">Node: %s</span>`, escapeHTML(node)))
	}
	b.WriteString(`</div>`)
	b.WriteString(fmt.Sprintf("<h1>%s</h1>\n", escapeHTML(name)))
	if subtitle != "" {
		b.WriteString(fmt.Sprintf(`<p class="subtitle">%s</p>`, escapeHTML(subtitle)))
	}
	b.WriteString(fmt.Sprintf(`<div class="import-line">import "%s"</div>`, escapeHTML(importPath)))
	b.WriteString(`</div>`)
	b.WriteString("\n")
	return b.String()
}

func collapseWS(s string) string {
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.ReplaceAll(s, "\r", " ")
	for strings.Contains(s, "  ") {
		s = strings.ReplaceAll(s, "  ", " ")
	}
	return strings.TrimSpace(s)
}

func escapeHTML(s string) string {
	s = strings.ReplaceAll(s, "<", "&lt;")
	s = strings.ReplaceAll(s, ">", "&gt;")
	return s
}

func escapeTable(s string) string {
	return strings.ReplaceAll(strings.ReplaceAll(s, "|", "\\|"), "\n", " ")
}

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

func needsRegen(path string) bool {
	data, err := os.ReadFile(path)
	if err != nil {
		return true
	}
	return !bytes.Contains(data, []byte("gox-doc-version: \""+docVersion+"\""))
}

func writeCoverage(root string, entries []coverageEntry) error {
	var b bytes.Buffer
	b.WriteString("[\n")
	for i, e := range entries {
		b.WriteString(fmt.Sprintf("  {\"package\":%q,\"symbol\":%q,\"kind\":%q,\"page\":%q,\"ok\":%v}", e.Pkg, e.Symbol, e.Kind, e.Page, e.OK))
		if i < len(entries)-1 {
			b.WriteString(",\n")
		}
	}
	b.WriteString("\n]\n")
	return os.WriteFile(filepath.Join(root, "coverage.json"), b.Bytes(), 0o644)
}

func envOr(k, def string) string {
	if v := os.Getenv(k); v != "" {
		return v
	}
	return def
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
