// Code generated by scripts/gendocs; DO NOT EDIT.
export const generatedSidebar = {
  '/packages/': [
    { text: 'Utilities', collapsed: false, items: [
      {
        text: 'cond',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/packages/cond/' },
          { text: '📖 Cookbook', link: '/packages/cond/cookbook' },
          { text: 'Coalesce', link: '/packages/cond/coalesce' },
          { text: 'CoalesceFn', link: '/packages/cond/coalesce-fn' },
          { text: 'CoalescePtr', link: '/packages/cond/coalesce-ptr' },
          { text: 'If', link: '/packages/cond/if' },
          { text: 'IfLazy', link: '/packages/cond/if-lazy' },
        ]
      },
      {
        text: 'slice',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/packages/slice/' },
          { text: '📖 Cookbook', link: '/packages/slice/cookbook' },
          { text: 'Chunk', link: '/packages/slice/chunk' },
          { text: 'Contains', link: '/packages/slice/contains' },
          { text: 'Every', link: '/packages/slice/every' },
          { text: 'Filter', link: '/packages/slice/filter' },
          { text: 'Find', link: '/packages/slice/find' },
          { text: 'FindIndex', link: '/packages/slice/find-index' },
          { text: 'Flatten', link: '/packages/slice/flatten' },
          { text: 'GroupBy', link: '/packages/slice/group-by' },
          { text: 'Map', link: '/packages/slice/map' },
          { text: 'Reduce', link: '/packages/slice/reduce' },
          { text: 'Some', link: '/packages/slice/some' },
          { text: 'SortBy', link: '/packages/slice/sort-by' },
          { text: 'Uniq', link: '/packages/slice/uniq' },
        ]
      },
      {
        text: 'maputil',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/packages/maputil/' },
          { text: '📖 Cookbook', link: '/packages/maputil/cookbook' },
          { text: 'Clone', link: '/packages/maputil/clone' },
          { text: 'Get', link: '/packages/maputil/get' },
          { text: 'Invert', link: '/packages/maputil/invert' },
          { text: 'Keys', link: '/packages/maputil/keys' },
          { text: 'Merge', link: '/packages/maputil/merge' },
          { text: 'Omit', link: '/packages/maputil/omit' },
          { text: 'Pick', link: '/packages/maputil/pick' },
          { text: 'Set', link: '/packages/maputil/set' },
          { text: 'Values', link: '/packages/maputil/values' },
        ]
      },
      {
        text: 'str',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/packages/str/' },
          { text: '📖 Cookbook', link: '/packages/str/cookbook' },
          { text: 'Camel', link: '/packages/str/camel' },
          { text: 'Capitalize', link: '/packages/str/capitalize' },
          { text: 'IsBlank', link: '/packages/str/is-blank' },
          { text: 'PadEnd', link: '/packages/str/pad-end' },
          { text: 'PadStart', link: '/packages/str/pad-start' },
          { text: 'Pascal', link: '/packages/str/pascal' },
          { text: 'Slug', link: '/packages/str/slug' },
          { text: 'Snake', link: '/packages/str/snake' },
          { text: 'Truncate', link: '/packages/str/truncate' },
        ]
      },
      {
        text: 'set',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/packages/set/' },
          { text: 'Set', link: '/packages/set/set' },
          { text: 'Set.Difference', link: '/packages/set/set-difference' },
          { text: 'Set.Intersection', link: '/packages/set/set-intersection' },
          { text: 'Set.New', link: '/packages/set/set-new' },
          { text: 'Set.Union', link: '/packages/set/set-union' },
        ]
      },
      {
        text: 'buffer',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/packages/buffer/' },
          { text: 'Compare', link: '/packages/buffer/compare' },
          { text: 'Equals', link: '/packages/buffer/equals' },
          { text: 'Buffer', link: '/packages/buffer/buffer' },
          { text: 'Buffer.Concat', link: '/packages/buffer/buffer-concat' },
          { text: 'Buffer.From', link: '/packages/buffer/buffer-from' },
          { text: 'Buffer.FromString', link: '/packages/buffer/buffer-from-string' },
        ]
      },
      {
        text: 'async',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/packages/async/' },
          { text: '📖 Cookbook', link: '/packages/async/cookbook' },
          { text: 'After', link: '/packages/async/after' },
          { text: 'All', link: '/packages/async/all' },
          { text: 'Race', link: '/packages/async/race' },
          { text: 'Retry', link: '/packages/async/retry' },
          { text: 'Sleep', link: '/packages/async/sleep' },
          { text: 'Timeout', link: '/packages/async/timeout' },
          { text: 'RetryConfig', link: '/packages/async/retry-config' },
        ]
      },
      {
        text: 'path',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/packages/path/' },
          { text: 'Basename', link: '/packages/path/basename' },
          { text: 'Dirname', link: '/packages/path/dirname' },
          { text: 'Extname', link: '/packages/path/extname' },
          { text: 'IsAbs', link: '/packages/path/is-abs' },
          { text: 'Join', link: '/packages/path/join' },
          { text: 'Resolve', link: '/packages/path/resolve' },
        ]
      },
      {
        text: 'url',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/packages/url/' },
          { text: 'EncodeQuery', link: '/packages/url/encode-query' },
          { text: 'Format', link: '/packages/url/format' },
          { text: 'ParseQuery', link: '/packages/url/parse-query' },
          { text: 'Resolve', link: '/packages/url/resolve' },
          { text: 'URL', link: '/packages/url/url' },
          { text: 'URL.Parse', link: '/packages/url/url-parse' },
        ]
      },
    ]},
    { text: 'I/O & OS', collapsed: false, items: [
      {
        text: 'env',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/packages/env/' },
          { text: '📖 Cookbook', link: '/packages/env/cookbook' },
          { text: 'Get', link: '/packages/env/get' },
          { text: 'GetBool', link: '/packages/env/get-bool' },
          { text: 'GetDuration', link: '/packages/env/get-duration' },
          { text: 'GetInt', link: '/packages/env/get-int' },
          { text: 'Load', link: '/packages/env/load' },
          { text: 'MustGet', link: '/packages/env/must-get' },
          { text: 'Set', link: '/packages/env/set' },
        ]
      },
      {
        text: 'fs',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/packages/fs/' },
          { text: '📖 Cookbook', link: '/packages/fs/cookbook' },
          { text: 'Copy', link: '/packages/fs/copy' },
          { text: 'Exists', link: '/packages/fs/exists' },
          { text: 'Mkdir', link: '/packages/fs/mkdir' },
          { text: 'ReadDir', link: '/packages/fs/read-dir' },
          { text: 'ReadFile', link: '/packages/fs/read-file' },
          { text: 'Remove', link: '/packages/fs/remove' },
          { text: 'Stat', link: '/packages/fs/stat' },
          { text: 'WriteFile', link: '/packages/fs/write-file' },
        ]
      },
      {
        text: 'err',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/packages/err/' },
          { text: '📖 Cookbook', link: '/packages/err/cookbook' },
          { text: 'As', link: '/packages/err/as' },
          { text: 'Is', link: '/packages/err/is' },
          { text: 'AppError', link: '/packages/err/app-error' },
          { text: 'AppError.BadRequest', link: '/packages/err/app-error-bad-request' },
          { text: 'AppError.Forbidden', link: '/packages/err/app-error-forbidden' },
          { text: 'AppError.Internal', link: '/packages/err/app-error-internal' },
          { text: 'AppError.New', link: '/packages/err/app-error-new' },
          { text: 'AppError.NotFound', link: '/packages/err/app-error-not-found' },
          { text: 'AppError.Unauthorized', link: '/packages/err/app-error-unauthorized' },
          { text: 'AppError.Wrap', link: '/packages/err/app-error-wrap' },
        ]
      },
      {
        text: 'exec',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/packages/exec/' },
          { text: 'Exec', link: '/packages/exec/exec' },
          { text: 'Cmd', link: '/packages/exec/cmd' },
          { text: 'Cmd.Command', link: '/packages/exec/cmd-command' },
        ]
      },
      {
        text: 'osutil',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/packages/osutil/' },
          { text: 'Arch', link: '/packages/osutil/arch' },
          { text: 'CPUs', link: '/packages/osutil/cp-us' },
          { text: 'Homedir', link: '/packages/osutil/homedir' },
          { text: 'Hostname', link: '/packages/osutil/hostname' },
          { text: 'Platform', link: '/packages/osutil/platform' },
          { text: 'TempDir', link: '/packages/osutil/temp-dir' },
          { text: 'UserInfoNumeric', link: '/packages/osutil/user-info-numeric' },
          { text: 'User', link: '/packages/osutil/user' },
          { text: 'User.UserInfo', link: '/packages/osutil/user-user-info' },
        ]
      },
      {
        text: 'stream',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/packages/stream/' },
          { text: 'Pipe', link: '/packages/stream/pipe' },
          { text: 'ReadAll', link: '/packages/stream/read-all' },
          { text: 'TeeReader', link: '/packages/stream/tee-reader' },
          { text: 'Transform', link: '/packages/stream/transform' },
        ]
      },
      {
        text: 'compress',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/packages/compress/' },
          { text: 'Gunzip', link: '/packages/compress/gunzip' },
          { text: 'Gzip', link: '/packages/compress/gzip' },
          { text: 'GzipReader', link: '/packages/compress/gzip-reader' },
          { text: 'GzipWriter', link: '/packages/compress/gzip-writer' },
        ]
      },
      {
        text: 'csv',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/packages/csv/' },
          { text: 'ParseString', link: '/packages/csv/parse-string' },
          { text: 'Read', link: '/packages/csv/read' },
          { text: 'ReadAll', link: '/packages/csv/read-all' },
          { text: 'Write', link: '/packages/csv/write' },
        ]
      },
      {
        text: 'archive',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/packages/archive/' },
          { text: 'TarCreate', link: '/packages/archive/tar-create' },
          { text: 'TarExtract', link: '/packages/archive/tar-extract' },
          { text: 'ZipCreate', link: '/packages/archive/zip-create' },
          { text: 'ZipCreateEntries', link: '/packages/archive/zip-create-entries' },
          { text: 'ZipExtract', link: '/packages/archive/zip-extract' },
          { text: 'FileEntry', link: '/packages/archive/file-entry' },
        ]
      },
    ]},
    { text: 'Web', collapsed: false, items: [
      {
        text: 'http',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/packages/http/' },
          { text: '📖 Cookbook', link: '/packages/http/cookbook' },
          { text: 'SaveUploadedFile', link: '/packages/http/save-uploaded-file' },
          { text: 'App', link: '/packages/http/app' },
          { text: 'CORSOptions', link: '/packages/http/cors-options' },
          { text: 'Ctx', link: '/packages/http/ctx' },
          { text: 'EventStream', link: '/packages/http/event-stream' },
          { text: 'Handler', link: '/packages/http/handler' },
          { text: 'MemoryStore', link: '/packages/http/memory-store' },
          { text: 'Middleware', link: '/packages/http/middleware' },
          { text: 'MultipartForm', link: '/packages/http/multipart-form' },
          { text: 'RateLimitOptions', link: '/packages/http/rate-limit-options' },
          { text: 'SessionOptions', link: '/packages/http/session-options' },
          { text: 'SessionStore', link: '/packages/http/session-store' },
          { text: 'WSHandler', link: '/packages/http/ws-handler' },
          { text: 'Middleware.CORS', link: '/packages/http/middleware-cors' },
          { text: 'Middleware.Logger', link: '/packages/http/middleware-logger' },
          { text: 'App.New', link: '/packages/http/app-new' },
          { text: 'MemoryStore.NewMemoryStore', link: '/packages/http/memory-store-new-memory-store' },
          { text: 'MultipartForm.ParseMultipart', link: '/packages/http/multipart-form-parse-multipart' },
          { text: 'Middleware.RateLimit', link: '/packages/http/middleware-rate-limit' },
          { text: 'Middleware.Recover', link: '/packages/http/middleware-recover' },
          { text: 'EventStream.SSE', link: '/packages/http/event-stream-sse' },
          { text: 'Handler.SSEHandler', link: '/packages/http/handler-sse-handler' },
          { text: 'Middleware.Security', link: '/packages/http/middleware-security' },
          { text: 'Middleware.SessionMiddleware', link: '/packages/http/middleware-session-middleware' },
        ]
      },
      {
        text: 'client',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/packages/client/' },
          { text: '📖 Cookbook', link: '/packages/client/cookbook' },
          { text: 'SetDefaultClient', link: '/packages/client/set-default-client' },
          { text: 'Client', link: '/packages/client/client' },
          { text: 'RequestOpts', link: '/packages/client/request-opts' },
          { text: 'Response', link: '/packages/client/response' },
          { text: 'Response.Fetch', link: '/packages/client/response-fetch' },
          { text: 'RequestOpts.JSONBody', link: '/packages/client/request-opts-json-body' },
          { text: 'Client.New', link: '/packages/client/client-new' },
          { text: 'RequestOpts.WithHeaders', link: '/packages/client/request-opts-with-headers' },
          { text: 'RequestOpts.WithMethod', link: '/packages/client/request-opts-with-method' },
          { text: 'RequestOpts.WithQuery', link: '/packages/client/request-opts-with-query' },
        ]
      },
      {
        text: 'log',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/packages/log/' },
          { text: '📖 Cookbook', link: '/packages/log/cookbook' },
          { text: 'SetDefault', link: '/packages/log/set-default' },
          { text: 'Logger', link: '/packages/log/logger' },
          { text: 'Logger.Default', link: '/packages/log/logger-default' },
          { text: 'Logger.New', link: '/packages/log/logger-new' },
          { text: 'Logger.NewWithLevel', link: '/packages/log/logger-new-with-level' },
        ]
      },
      {
        text: 'ws',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/packages/ws/' },
          { text: '📖 Cookbook', link: '/packages/ws/cookbook' },
          { text: 'Conn', link: '/packages/ws/conn' },
          { text: 'Server', link: '/packages/ws/server' },
          { text: 'Upgrader', link: '/packages/ws/upgrader' },
          { text: 'WSHandler', link: '/packages/ws/ws-handler' },
          { text: 'Conn.Dial', link: '/packages/ws/conn-dial' },
          { text: 'Server.NewServer', link: '/packages/ws/server-new-server' },
          { text: 'Conn.Upgrade', link: '/packages/ws/conn-upgrade' },
          { text: 'DefaultUpgrader', link: '/packages/ws/default-upgrader' },
        ]
      },
    ]},
    { text: 'Data', collapsed: false, items: [
      {
        text: 'json',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/packages/json/' },
          { text: '📖 Cookbook', link: '/packages/json/cookbook' },
          { text: 'MustParse', link: '/packages/json/must-parse' },
          { text: 'MustStringify', link: '/packages/json/must-stringify' },
          { text: 'Parse', link: '/packages/json/parse' },
          { text: 'ParseFile', link: '/packages/json/parse-file' },
          { text: 'Pretty', link: '/packages/json/pretty' },
          { text: 'Stringify', link: '/packages/json/stringify' },
          { text: 'WriteFile', link: '/packages/json/write-file' },
        ]
      },
      {
        text: 'validate',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/packages/validate/' },
          { text: '📖 Cookbook', link: '/packages/validate/cookbook' },
          { text: 'Array', link: '/packages/validate/array' },
          { text: 'Bool', link: '/packages/validate/bool' },
          { text: 'Float', link: '/packages/validate/float' },
          { text: 'Int', link: '/packages/validate/int' },
          { text: 'MustValidate', link: '/packages/validate/must-validate' },
          { text: 'ObjectField', link: '/packages/validate/object-field' },
          { text: 'ParseJSON', link: '/packages/validate/parse-json' },
          { text: 'String', link: '/packages/validate/string' },
          { text: 'Validate', link: '/packages/validate/validate' },
          { text: 'ValidateSchema', link: '/packages/validate/validate-schema' },
          { text: 'Field', link: '/packages/validate/field' },
          { text: 'Schema', link: '/packages/validate/schema' },
          { text: 'ValidationError', link: '/packages/validate/validation-error' },
          { text: 'Schema.Object', link: '/packages/validate/schema-object' },
        ]
      },
      {
        text: 'db',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/packages/db/' },
          { text: '📖 Cookbook', link: '/packages/db/cookbook' },
          { text: 'DB', link: '/packages/db/db' },
          { text: 'Query', link: '/packages/db/query' },
          { text: 'Tx', link: '/packages/db/tx' },
          { text: 'DB.MustOpen', link: '/packages/db/db-must-open' },
          { text: 'DB.Open', link: '/packages/db/db-open' },
        ]
      },
      {
        text: 'redis',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/packages/redis/' },
          { text: '📖 Cookbook', link: '/packages/redis/cookbook' },
          { text: 'Client', link: '/packages/redis/client' },
          { text: 'Message', link: '/packages/redis/message' },
          { text: 'Client.New', link: '/packages/redis/client-new' },
          { text: 'Client.NewFromClient', link: '/packages/redis/client-new-from-client' },
        ]
      },
      {
        text: 'mongo',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/packages/mongo/' },
          { text: '📖 Cookbook', link: '/packages/mongo/cookbook' },
          { text: 'Eq', link: '/packages/mongo/eq' },
          { text: 'Gt', link: '/packages/mongo/gt' },
          { text: 'In', link: '/packages/mongo/in' },
          { text: 'Set', link: '/packages/mongo/set' },
          { text: 'Client', link: '/packages/mongo/client' },
          { text: 'Collection', link: '/packages/mongo/collection' },
          { text: 'Database', link: '/packages/mongo/database' },
          { text: 'Client.Connect', link: '/packages/mongo/client-connect' },
        ]
      },
    ]},
    { text: 'Security', collapsed: false, items: [
      {
        text: 'crypto',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/packages/crypto/' },
          { text: '📖 Cookbook', link: '/packages/crypto/cookbook' },
          { text: 'CheckPassword', link: '/packages/crypto/check-password' },
          { text: 'HMACSHA256', link: '/packages/crypto/hmacsha256' },
          { text: 'HashPassword', link: '/packages/crypto/hash-password' },
          { text: 'RandomBytes', link: '/packages/crypto/random-bytes' },
          { text: 'RandomString', link: '/packages/crypto/random-string' },
          { text: 'SHA256', link: '/packages/crypto/sha256' },
        ]
      },
      {
        text: 'jwt',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/packages/jwt/' },
          { text: '📖 Cookbook', link: '/packages/jwt/cookbook' },
          { text: 'Decode', link: '/packages/jwt/decode' },
          { text: 'Sign', link: '/packages/jwt/sign' },
          { text: 'Verify', link: '/packages/jwt/verify' },
          { text: 'SignOptions', link: '/packages/jwt/sign-options' },
        ]
      },
      {
        text: 'id',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/packages/id/' },
          { text: 'MustParseUUID', link: '/packages/id/must-parse-uuid' },
          { text: 'NewNanoID', link: '/packages/id/new-nano-id' },
          { text: 'NewUUID', link: '/packages/id/new-uuid' },
          { text: 'ParseUUID', link: '/packages/id/parse-uuid' },
        ]
      },
      {
        text: 'auth',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/packages/auth/' },
          { text: '📖 Cookbook', link: '/packages/auth/cookbook' },
          { text: 'APIKey', link: '/packages/auth/api-key' },
          { text: 'Basic', link: '/packages/auth/basic' },
          { text: 'Bearer', link: '/packages/auth/bearer' },
          { text: 'GetAPIKey', link: '/packages/auth/get-api-key' },
          { text: 'GetBasicUser', link: '/packages/auth/get-basic-user' },
          { text: 'GetClaims', link: '/packages/auth/get-claims' },
          { text: 'APIKeyOpts', link: '/packages/auth/api-key-opts' },
          { text: 'BearerOptions', link: '/packages/auth/bearer-options' },
        ]
      },
    ]},
    { text: 'Infrastructure', collapsed: false, items: [
      {
        text: 'cache',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/packages/cache/' },
          { text: '📖 Cookbook', link: '/packages/cache/cookbook' },
          { text: 'Cache', link: '/packages/cache/cache' },
          { text: 'Cache.New', link: '/packages/cache/cache-new' },
        ]
      },
      {
        text: 'event',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/packages/event/' },
          { text: 'Emitter', link: '/packages/event/emitter' },
          { text: 'Emitter.New', link: '/packages/event/emitter-new' },
        ]
      },
      {
        text: 'cron',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/packages/cron/' },
          { text: '📖 Cookbook', link: '/packages/cron/cookbook' },
          { text: 'Parse', link: '/packages/cron/parse' },
          { text: 'JobID', link: '/packages/cron/job-id' },
          { text: 'Scheduler', link: '/packages/cron/scheduler' },
          { text: 'Scheduler.New', link: '/packages/cron/scheduler-new' },
        ]
      },
      {
        text: 'queue',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/packages/queue/' },
          { text: 'Client', link: '/packages/queue/client' },
          { text: 'EnqueueOpts', link: '/packages/queue/enqueue-opts' },
          { text: 'Handler', link: '/packages/queue/handler' },
          { text: 'ServeMux', link: '/packages/queue/serve-mux' },
          { text: 'Worker', link: '/packages/queue/worker' },
          { text: 'Client.New', link: '/packages/queue/client-new' },
          { text: 'ServeMux.NewServeMux', link: '/packages/queue/serve-mux-new-serve-mux' },
          { text: 'Worker.NewWorker', link: '/packages/queue/worker-new-worker' },
        ]
      },
      {
        text: 'mail',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/packages/mail/' },
          { text: 'BuildMIME', link: '/packages/mail/build-mime' },
          { text: 'Send', link: '/packages/mail/send' },
          { text: 'Message', link: '/packages/mail/message' },
          { text: 'SMTPConfig', link: '/packages/mail/smtp-config' },
        ]
      },
      {
        text: 'time',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/packages/time/' },
          { text: 'Add', link: '/packages/time/add' },
          { text: 'Diff', link: '/packages/time/diff' },
          { text: 'EndOfDay', link: '/packages/time/end-of-day' },
          { text: 'EndOfMonth', link: '/packages/time/end-of-month' },
          { text: 'Format', link: '/packages/time/format' },
          { text: 'Now', link: '/packages/time/now' },
          { text: 'Parse', link: '/packages/time/parse' },
          { text: 'ParseDuration', link: '/packages/time/parse-duration' },
          { text: 'StartOfDay', link: '/packages/time/start-of-day' },
          { text: 'StartOfMonth', link: '/packages/time/start-of-month' },
          { text: 'LayoutDate', link: '/packages/time/layout-date' },
          { text: 'LayoutDateTime', link: '/packages/time/layout-date-time' },
          { text: 'LayoutISO', link: '/packages/time/layout-iso' },
          { text: 'LayoutTime', link: '/packages/time/layout-time' },
        ]
      },
      {
        text: 'semver',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/packages/semver/' },
          { text: 'Compare', link: '/packages/semver/compare' },
          { text: 'Inc', link: '/packages/semver/inc' },
          { text: 'Satisfies', link: '/packages/semver/satisfies' },
          { text: 'Version', link: '/packages/semver/version' },
          { text: 'Version.Parse', link: '/packages/semver/version-parse' },
        ]
      },
    ]},
  ]
}
